// Icon — static lucide-react registry replacing the prototype's CDN innerHTML hack.
// Registry keys are the EXACT kebab-case names referenced by string across the app.
import type { CSSProperties, HTMLAttributes } from 'react';
import type { LucideIcon } from 'lucide-react';
import {
  ArrowLeftRight,
  Banknote,
  Bell,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  CircleCheck,
  CircleCheckBig,
  CirclePause,
  Coins,
  CreditCard,
  Database,
  DollarSign,
  Download,
  Eye,
  EyeOff,
  FileText,
  FolderCog,
  Globe,
  Hash,
  House,
  Info,
  Link,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Menu,
  Package,
  Pause,
  PenLine,
  Percent,
  Phone,
  Play,
  Plus,
  Printer,
  Receipt,
  RefreshCw,
  Repeat,
  RotateCcw,
  ScanBarcode,
  ScanLine,
  Search,
  SearchX,
  Settings,
  Shield,
  Shuffle,
  Smartphone,
  Store,
  Truck,
  Tag,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  User,
  UserCheck,
  UserCog,
  UserPlus,
  UserRound,
  UserX,
  Users,
  Volume2,
  WifiOff,
  X,
} from 'lucide-react';

const REGISTRY: Record<string, LucideIcon> = {
  home: House,
  'scan-barcode': ScanBarcode,
  'scan-line': ScanLine,
  'pause-circle': CirclePause,
  receipt: Receipt,
  package: Package,
  users: Users,
  'user-cog': UserCog,
  settings: Settings,
  'user-round': UserRound,
  'log-out': LogOut,
  menu: Menu,
  x: X,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevrons-left': ChevronsLeft,
  'chevrons-right': ChevronsRight,
  info: Info,
  banknote: Banknote,
  'credit-card': CreditCard,
  'arrow-left-right': ArrowLeftRight,
  smartphone: Smartphone,
  'dollar-sign': DollarSign,
  plus: Plus,
  'check-circle-2': CircleCheckBig,
  'check-circle': CircleCheck,
  check: Check,
  printer: Printer,
  'wifi-off': WifiOff,
  'edit-3': PenLine,
  'trash-2': Trash2,
  'user-plus': UserPlus,
  lock: Lock,
  'alert-triangle': TriangleAlert,
  repeat: Repeat,
  'folder-cog': FolderCog,
  'search-x': SearchX,
  pause: Pause,
  play: Play,
  'user-check': UserCheck,
  'user-x': UserX,
  user: User,
  search: Search,
  'rotate-ccw': RotateCcw,
  store: Store,
  truck: Truck,
  hash: Hash,
  phone: Phone,
  'map-pin': MapPin,
  percent: Percent,
  coins: Coins,
  'file-text': FileText,
  mail: Mail,
  bell: Bell,
  'volume-2': Volume2,
  globe: Globe,
  'refresh-cw': RefreshCw,
  link: Link,
  database: Database,
  shield: Shield,
  eye: Eye,
  'eye-off': EyeOff,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  shuffle: Shuffle,
  tag: Tag,
  download: Download,
};

export interface IconProps extends Omit<
  HTMLAttributes<HTMLSpanElement>,
  'color'
> {
  name: string;
  size?: number;
  color?: CSSProperties['color'];
}

export function Icon({ name, size = 22, color, style, ...rest }: IconProps) {
  // Same stable <span> wrapper the prototype rendered — CSS targets it
  // (.iconbtn svg etc.) and expects the svg inside the span.
  const LucideCmp: LucideIcon | undefined = REGISTRY[name];
  return (
    <span
      style={{
        width: size,
        height: size,
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        flex: 'none',
        color,
        ...style,
      }}
      {...rest}
    >
      {LucideCmp && <LucideCmp size={size} style={{ display: 'block' }} />}
    </span>
  );
}
